# Generated by Django 4.1.5 on 2023-02-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="secret_key",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
