# Generated by Django 4.1.5 on 2023-02-25 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_customuser_secret_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivatedAlgorithm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("algorithm", models.CharField(max_length=100)),
                ("stock_name", models.CharField(max_length=100)),
                (
                    "investment_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "short_moving_avg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "long_moving_avg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "days_of_moving_avg",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "over_percentage_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "under_percentage_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "standard_deviation",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
