# Generated by Django 4.1.5 on 2023-02-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_activatedalgorithm"),
    ]

    operations = [
        migrations.AddField(
            model_name="activatedalgorithm",
            name="shares",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
