# Generated by Django 4.1.5 on 2023-02-27 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_activatedalgorithm_shares"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activatedalgorithm",
            name="long_moving_avg",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="activatedalgorithm",
            name="over_percentage_threshold",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="activatedalgorithm",
            name="short_moving_avg",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="activatedalgorithm",
            name="standard_deviation",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="activatedalgorithm",
            name="under_percentage_threshold",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
