# Generated by Django 4.1.5 on 2023-02-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_activatedalgorithm_long_moving_avg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activatedalgorithm",
            name="days_of_moving_avg",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
