# Generated by Django 4.1.5 on 2023-02-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_alter_activatedalgorithm_days_of_moving_avg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activatedalgorithm",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
