# Generated by Django 4.1.5 on 2023-03-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_activatedalgorithm_long_moving_avg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activatedalgorithm",
            name="investment_amount",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="activatedalgorithm",
            name="over_percentage_threshold",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="activatedalgorithm",
            name="standard_deviation",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="activatedalgorithm",
            name="under_percentage_threshold",
            field=models.FloatField(default=0),
        ),
    ]
