# Generated by Django 4.1.5 on 2023-03-10 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_alter_activatedalgorithm_investment_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activatedalgorithm",
            name="shares",
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name="TradeLog",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("trade_time", models.DateTimeField(auto_now=True)),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("sell", "sell"), ("buy", "buy")], max_length=4
                    ),
                ),
                ("algorithm_name", models.CharField(max_length=100)),
                ("stock_name", models.CharField(max_length=100)),
                ("shares", models.FloatField(default=0)),
                ("avg_price", models.FloatField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
